In [1]:
!pip install mne
!pip install pandas
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 37.5 MB/s eta 0:00:00


In [2]:

!unzip /content/Real\ Time\ Task\ Classification\ -\ Copy.zip


Archive:  /content/Real Time Task Classification - Copy.zip
   creating: Real Time Task Classification - Copy/
  inflating: Real Time Task Classification - Copy/intended.h5  
  inflating: Real Time Task Classification - Copy/scaler.pkl  
   creating: Real Time Task Classification - Copy/T1a/
  inflating: Real Time Task Classification - Copy/T1a/20240909-014825-Epoc X-raw.pcl  
   creating: Real Time Task Classification - Copy/T1a/fif/
  inflating: Real Time Task Classification - Copy/T1a/fif/20240909-014825-Epoc X-raw.fif  
  inflating: Real Time Task Classification - Copy/T1a/fif/raw_eeg_data.csv  
   creating: Real Time Task Classification - Copy/T1b/
  inflating: Real Time Task Classification - Copy/T1b/20240909-015206-Epoc X-raw.pcl  
   creating: Real Time Task Classification - Copy/T1b/fif/
  inflating: Real Time Task Classification - Copy/T1b/fif/20240909-015206-Epoc X-raw.fif  
   creating: Real Time Task Classification - Copy/T2a/
  inflating: Real Time Task Classification - C

In [33]:
import mne

# Imaginary and real file paths
T1_file_path = [r'/content/Real Time Task Classification - Copy/T1a/fif/20240909-014825-Epoc X-raw.fif']

T2_file_path = [r'/content/Real Time Task Classification - Copy/T2a/fif/20240909-015509-Epoc X-raw.fif']

T3_file_path = [r'/content/Real Time Task Classification - Copy/T3a/fif/20240909-020145-Epoc X-raw.fif']

T4_file_path = [r'/content/Real Time Task Classification - Copy/T4a/fif/20240909-020824-Epoc X-raw.fif']

T5_file_path = [r'/content/Real Time Task Classification - Copy/T5a/fif/20240909-021529-Epoc X-raw.fif']


# Loop through imaginary file paths
for file_path in T1_file_path:
    try:
        raw_data = mne.io.read_raw_fif(file_path, preload=True)
        print(f"Loaded {file_path}")
        print(raw_data.info)
    except FileNotFoundError:
        print(f"File not found: {file_path}")

for file_path in T2_file_path:
    try:
        raw_data = mne.io.read_raw_fif(file_path, preload=True)
        print(f"Loaded {file_path}")
        print(raw_data.info)
    except FileNotFoundError:
        print(f"File not found: {file_path}")

for file_path in T3_file_path:
    try:
        raw_data = mne.io.read_raw_fif(file_path, preload=True)
        print(f"Loaded {file_path}")
        print(raw_data.info)
    except FileNotFoundError:
        print(f"File not found: {file_path}")


for file_path in T4_file_path:
    try:
        raw_data = mne.io.read_raw_fif(file_path, preload=True)
        print(f"Loaded {file_path}")
        print(raw_data.info)
    except FileNotFoundError:
        print(f"File not found: {file_path}")

for file_path in T5_file_path:
    try:
        raw_data = mne.io.read_raw_fif(file_path, preload=True)
        print(f"Loaded {file_path}")
        print(raw_data.info)
        print(len(raw_data))
    except FileNotFoundError:
        print(f"File not found: {file_path}")


Opening raw data file /content/Real Time Task Classification - Copy/T1a/fif/20240909-014825-Epoc X-raw.fif...
Isotrak not found
    Range : 0 ... 21055 =      0.000 ...   164.492 secs
Ready.
Reading 0 ... 21055  =      0.000 ...   164.492 secs...
Loaded /content/Real Time Task Classification - Copy/T1a/fif/20240909-014825-Epoc X-raw.fif
<Info | 9 non-empty values
 bads: []
 ch_names: TRIGGER, AF3, F7, F3, FC5, T7, P7, O1, O2, P8, T8, FC6, F4, F8, AF4
 chs: 1 Stimulus, 14 EEG
 custom_ref_applied: False
 file_id: 4 items (dict)
 highpass: 0.0 Hz
 lowpass: 64.0 Hz
 meas_date: unspecified
 meas_id: 4 items (dict)
 nchan: 15
 projs: []
 sfreq: 128.0 Hz
>
Opening raw data file /content/Real Time Task Classification - Copy/T2a/fif/20240909-015509-Epoc X-raw.fif...
Isotrak not found
    Range : 0 ... 20447 =      0.000 ...   159.742 secs
Ready.
Reading 0 ... 20447  =      0.000 ...   159.742 secs...
Loaded /content/Real Time Task Classification - Copy/T2a/fif/20240909-015509-Epoc X-raw.fif
<In

In [34]:
import mne

def read_data(file_path):
    ch_names = ['AF3', 'F7', 'F3', 'FC5', 'T7', 'P7', 'O1', 'O2', 'P8', 'T8', 'FC6', 'F4', 'F8', 'AF4']
    # ch_names = [ 'F7', 'F3', 'FC5', 'T7', 'P7', 'O1', 'O2']
    data = mne.io.read_raw_fif(file_path, preload=True)
    data.pick_channels(ch_names)
    # data.set_eeg_reference()
    # data.filter(l_freq=4, h_freq=25)
    epochs = mne.make_fixed_length_epochs(data, duration=5, overlap=4)
    epochs = epochs.get_data()
    print(epochs)
    return epochs

T1_epochs_array = [read_data(subject) for subject in T1_file_path]
T2_epochs_array = [read_data(subject) for subject in T2_file_path]
T3_epochs_array = [read_data(subject) for subject in T3_file_path]
T4_epochs_array = [read_data(subject) for subject in T4_file_path]
T5_epochs_array = [read_data(subject) for subject in T5_file_path]

Opening raw data file /content/Real Time Task Classification - Copy/T1a/fif/20240909-014825-Epoc X-raw.fif...
Isotrak not found
    Range : 0 ... 21055 =      0.000 ...   164.492 secs
Ready.
Reading 0 ... 21055  =      0.000 ...   164.492 secs...
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
Not setting metadata
160 matching events found
No baseline correction applied
0 projection items activated
Using data from preloaded Raw for 160 events and 640 original time points ...
0 bad epochs dropped
[[[0.00430474 0.00431487 0.00428385 ... 0.00430436 0.00430833 0.00429   ]
  [0.0044859  0.00449423 0.00446551 ... 0.00428218 0.00428423 0.00427192]
  [0.00431397 0.00431885 0.00430013 ... 0.00431769 0.00432128 0.00431372]
  ...
  [0.00438333 0.00437808 0.00436346 ... 0.00446897 0.00447705 0.00447487]
  [0.00434769 0.00435872 0.00433795 ... 0.00437859 0.00438603 0.00437205]
  [0.00449064 0.00450372 0.00448141 ... 0.00445423 0.00444385 0.00442692]]

 [[0.00432282 0

In [35]:
print("data files: ",len(T1_epochs_array))
print("epochs: ",len(T1_epochs_array[0]))
print("Channels: ",len(T1_epochs_array[0][0]))
print("data point in each epoch:",len(T1_epochs_array[0][0][0]))

data files:  1
epochs:  160
Channels:  14
data point in each epoch: 640


In [36]:
print("support T1",len(T1_epochs_array[0]))
print("support T2",len(T2_epochs_array[0]))
print("support T3",len(T3_epochs_array[0]))
print("support T4",len(T4_epochs_array[0]))
print("support T5",len(T5_epochs_array[0]))

support T1 160
support T2 155
support T3 151
support T4 160
support T5 145


In [37]:
T1_epochs_labels=[len(i)*[0] for i in T1_epochs_array]
T2_epochs_labels=[len(i)*[1] for i in T2_epochs_array]
T3_epochs_labels=[len(i)*[2] for i in T3_epochs_array]
T4_epochs_labels=[len(i)*[3] for i in T4_epochs_array]
T5_epochs_labels=[len(i)*[4] for i in T5_epochs_array]

In [38]:
data_list=T1_epochs_array+T2_epochs_array+T3_epochs_array+T4_epochs_array+T5_epochs_array
label_list=T1_epochs_labels+T2_epochs_labels+T3_epochs_labels+T4_epochs_labels+T5_epochs_labels
print(len(data_list),len(data_list[0]),len(data_list[0][0]),len(data_list[0][0][0]),len(label_list[0]))

5 160 14 640 160


In [39]:
import numpy as np
data_array=np.vstack(data_list)
label_array=np.hstack(label_list)
print(data_array.shape)
data_array=np.moveaxis(data_array,1,2)

print(data_array.shape,label_array.shape)

(771, 14, 640)
(771, 640, 14) (771,)


In [40]:
len(data_array[0])

640

In [41]:
X=data_array
y=label_array

In [42]:
from tensorflow.keras.layers import Conv1D, BatchNormalization, LeakyReLU, MaxPool1D, \
    GlobalAveragePooling1D, Dense, Dropout, AveragePooling1D
from tensorflow.keras.models import Sequential
from tensorflow.keras.backend import clear_session

def cnnmodel():
    clear_session()
    model = Sequential()

    # First Conv Layer
    model.add(Conv1D(filters=8, kernel_size=3, strides=1, input_shape=(640, 14)))
    model.add(BatchNormalization())
    model.add(LeakyReLU())
    model.add(MaxPool1D(pool_size=2, strides=2))

    # Second Conv Layer
    model.add(Conv1D(filters=8, kernel_size=3, strides=1))
    model.add(BatchNormalization())  # Added BatchNormalization to maintain consistency
    model.add(LeakyReLU())
    model.add(MaxPool1D(pool_size=2, strides=2))
    model.add(Dropout(0.3))

    # Third Conv Layer
    model.add(Conv1D(filters=8, kernel_size=3, strides=1))
    model.add(BatchNormalization())  # Added BatchNormalization
    model.add(LeakyReLU())
    model.add(AveragePooling1D(pool_size=2, strides=2))
    model.add(Dropout(0.3))

    # Fourth Conv Layer
    model.add(Conv1D(filters=8, kernel_size=3, strides=1))
    model.add(BatchNormalization())  # Added BatchNormalization
    model.add(LeakyReLU())
    model.add(AveragePooling1D(pool_size=2, strides=2))

    # Fifth Conv Layer
    model.add(Conv1D(filters=8, kernel_size=3, strides=1))
    model.add(BatchNormalization())  # Added BatchNormalization
    model.add(LeakyReLU())

    # Global Average Pooling and Final Dense Layer for 4 Classes
    model.add(GlobalAveragePooling1D())
    model.add(Dense(5, activation='softmax'))  # Changed to 5 output classes

    # Compile the model for multi-class classification
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

    return model

model = cnnmodel()
model.summary()


/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                      │ (None, 638, 8)              │             344 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization                  │ (None, 638, 8)              │              32 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ leaky_re_lu (LeakyReLU)              │ (None, 638, 8)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling1d (MaxPooling1D)         │ (None, 319, 8)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1d_1 (Conv1D)                    │ (None, 317, 8)              │             200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_1                │ (None, 317, 8)              │              32 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ leaky_re_lu_1 (LeakyReLU)            │ (None, 317, 8)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling1d_1 (MaxPooling1D)       │ (None, 158, 8)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 158, 8)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1d_2 (Conv1D)                    │ (None, 156, 8)              │             200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_2                │ (None, 156, 8)              │              32 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ leaky_re_lu_2 (LeakyReLU)            │ (None, 156, 8)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ average_pooling1d (AveragePooling1D) │ (None, 78, 8)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 78, 8)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1d_3 (Conv1D)                    │ (None, 76, 8)               │             200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_3                │ (None, 76, 8)               │              32 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ leaky_re_lu_3 (LeakyReLU)            │ (None, 76, 8)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ average_pooling1d_1                  │ (None, 38, 8)               │               0 │
│ (AveragePooling1D)                   │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1d_4 (Conv1D)                    │ (None, 36, 8)               │             2

 Total params: 1,349 (5.27 KB)

 Trainable params: 1,269 (4.96 KB)

 Non-trainable params: 80 (320.00 B)

In [43]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np


model = cnnmodel()
accuracy = []

train_features, test_features, train_labels, test_labels = train_test_split(
    data_array, label_array, test_size=0.4, random_state=4
)
train_features, val_features, train_labels, val_labels = train_test_split(
    train_features, train_labels, test_size=0.4, random_state=4
)
# Check the shapes of training features and labels
print("Shape of train_features:", train_features.shape)
print("Shape of train_labels:", train_labels.shape)

# Similarly, check validation and test shapes if needed
print("Shape of val_features:", val_features.shape)
print("Shape of val_labels:", val_labels.shape)
print("Shape of test_features:", test_features.shape)
print("Shape of test_labels:", test_labels.shape)

scaler = StandardScaler()
train_features = scaler.fit_transform(train_features.reshape(-1, train_features.shape[-1])).reshape(train_features.shape)
val_features = scaler.transform(val_features.reshape(-1, val_features.shape[-1])).reshape(val_features.shape)
test_features = scaler.transform(test_features.reshape(-1, test_features.shape[-1])).reshape(test_features.shape)
# Check the shapes of training features and labels
print("Shape of train_features:", train_features.shape)
print("Shape of train_labels:", train_labels.shape)

# Similarly, check validation and test shapes if needed
print("Shape of val_features:", val_features.shape)
print("Shape of val_labels:", val_labels.shape)
print("Shape of test_features:", test_features.shape)
print("Shape of test_labels:", test_labels.shape)



Shape of train_features: (277, 640, 14)
Shape of train_labels: (277,)
Shape of val_features: (185, 640, 14)
Shape of val_labels: (185,)
Shape of test_features: (309, 640, 14)
Shape of test_labels: (309,)
Shape of train_features: (277, 640, 14)
Shape of train_labels: (277,)
Shape of val_features: (185, 640, 14)
Shape of val_labels: (185,)
Shape of test_features: (309, 640, 14)
Shape of test_labels: (309,)


In [45]:

history = model.fit(train_features, train_labels, epochs=150, batch_size=128, validation_data=(val_features, val_labels))

val_accuracy = model.evaluate(val_features, val_labels)[1]
test_accuracy = model.evaluate(test_features, test_labels)[1]

print("Validation Accuracy:", val_accuracy)
print("Test Accuracy:", test_accuracy)

Epoch 1/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 7s 368ms/step - accuracy: 0.0788 - loss: 1.7497 - val_accuracy: 0.0811 - val_loss: 1.6183
Epoch 2/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.0995 - loss: 1.6951 - val_accuracy: 0.1189 - val_loss: 1.6048
Epoch 3/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 126ms/step - accuracy: 0.1463 - loss: 1.6487 - val_accuracy: 0.2757 - val_loss: 1.5948
Epoch 4/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 130ms/step - accuracy: 0.1982 - loss: 1.5976 - val_accuracy: 0.3838 - val_loss: 1.5864
Epoch 5/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 122ms/step - accuracy: 0.2151 - loss: 1.5555 - val_accuracy: 0.4162 - val_loss: 1.5787
Epoch 6/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 157ms/step - accuracy: 0.2572 - loss: 1.5180 - val_accuracy: 0.4378 - val_loss: 1.5712
Epoch 7/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 223ms/step - accuracy: 0.3183 - loss: 1.4994 - val_accuracy: 0.4432 - val_loss: 1.5628
Epoch 8/150
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 192ms/step - accuracy: 0.3273 - loss: 1.4826 - val_accuracy: 0.4486 - v

In [46]:
# Check the shapes of training features and labels
print("Shape of train_features:", train_features.shape)
print("Shape of train_labels:", train_labels.shape)

# Similarly, check validation and test shapes if needed
print("Shape of val_features:", val_features.shape)
print("Shape of val_labels:", val_labels.shape)
print("Shape of test_features:", test_features.shape)
print("Shape of test_labels:", test_labels.shape)


Shape of train_features: (277, 640, 14)
Shape of train_labels: (277,)
Shape of val_features: (185, 640, 14)
Shape of val_labels: (185,)
Shape of test_features: (309, 640, 14)
Shape of test_labels: (309,)


In [47]:
import tensorflow as tf
model.save('intended.h5')

In [48]:
data_array.shape

(771, 640, 14)

In [60]:
def classify_single_epoch(fif_file_path, model, scaler, epoch_idx=0):
    """
    Preprocess a single epoch of data from a .fif file and classify using the trained CNN model.

    Parameters:
        fif_file_path (str): Path to the .fif file.
        model (tf.keras.Model): Trained CNN model for classification.
        scaler (StandardScaler): Scaler fitted on training data to ensure consistent preprocessing.
        epoch_idx (int): Index of the epoch to process and classify.

    Returns:
        int: Predicted class for the selected epoch.
    """
    # Define EEG channels used during training
    ch_names = ['AF3', 'F7', 'F3', 'FC5', 'T7', 'P7', 'O1', 'O2', 'P8', 'T8', 'FC6', 'F4', 'F8', 'AF4']

    # Load and preprocess the .fif file
    try:
        raw_data = mne.io.read_raw_fif(fif_file_path, preload=True)
        raw_data.pick_channels(ch_names)  # Keep only required channels
    except Exception as e:
        raise ValueError(f"Error loading file {fif_file_path}: {str(e)}")

    # Segment the data into 5-second epochs
    epochs = mne.make_fixed_length_epochs(raw_data, duration=5, overlap=4).get_data()

    # Ensure the epoch index is valid
    if epoch_idx < 0 or epoch_idx >= epochs.shape[0]:
        raise IndexError(f"Epoch index {epoch_idx} is out of bounds. Total epochs: {epochs.shape[0]}")

    # Select the specified epoch
    single_epoch = epochs[epoch_idx]

    # Preprocess the epoch (scaling with the provided scaler)
    single_epoch = scaler.transform(single_epoch.T).T  # Transpose for scaling and then back

    # Adjust dimensions to match model input (samples, time, channels)
    single_epoch = np.expand_dims(single_epoch.T, axis=0)  # Shape: (1, time, channels)

    # Print the shape of the input
    print("Shape of input to the model:", single_epoch.shape)

    # Perform classification on the selected epoch
    prediction = model.predict(single_epoch)
    predicted_class = np.argmax(prediction, axis=1)[0]

    return predicted_class
# Assuming the scaler used during training is already available
predicted_class = classify_single_epoch(
    "/content/Real Time Task Classification - Copy/T2a/fif/20240909-015509-Epoc X-raw.fif",
    model,
    scaler,  # Use the training scaler here
    epoch_idx=153
)

print(f"Predicted class for epoch 0: {predicted_class}")


Opening raw data file /content/Real Time Task Classification - Copy/T2a/fif/20240909-015509-Epoc X-raw.fif...
Isotrak not found
    Range : 0 ... 20447 =      0.000 ...   159.742 secs
Ready.
Reading 0 ... 20447  =      0.000 ...   159.742 secs...
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
Not setting metadata
155 matching events found
No baseline correction applied
0 projection items activated
Using data from preloaded Raw for 155 events and 640 original time points ...
0 bad epochs dropped
Shape of input to the model: (1, 640, 14)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
Predicted class for epoch 0: 1
