In [ ]:
!pip install mne
!pip install pandas
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 56.8 MB/s eta 0:00:00


In [ ]:

!unzip /content/Sumit.zip



Archive:  /content/Sumit.zip
   creating: Sumit/
  inflating: Sumit/intended.h5       
  inflating: Sumit/scaler.pkl        
  inflating: Sumit/sumit.ipynb       
   creating: Sumit/T1a/
  inflating: Sumit/T1a/20241210-110330-Epoc X-raw.pcl  
   creating: Sumit/T1a/fif/
  inflating: Sumit/T1a/fif/20241210-110330-Epoc X-raw.fif  
   creating: Sumit/T1b/
  inflating: Sumit/T1b/20241210-110551-Epoc X-raw.pcl  
   creating: Sumit/T1b/fif/
  inflating: Sumit/T1b/fif/20241210-110551-Epoc X-raw.fif  
   creating: Sumit/T2a/
  inflating: Sumit/T2a/20241210-110820-Epoc X-raw.pcl  
   creating: Sumit/T2a/fif/
  inflating: Sumit/T2a/fif/20241210-110820-Epoc X-raw.fif  
   creating: Sumit/T2b/
  inflating: Sumit/T2b/20241210-111041-Epoc X-raw.pcl  
   creating: Sumit/T2b/fif/
  inflating: Sumit/T2b/fif/20241210-111041-Epoc X-raw.fif  
   creating: Sumit/T3a/
  inflating: Sumit/T3a/20241210-111304-Epoc X-raw.pcl  
   creating: Sumit/T3a/fif/
  inflating: Sumit/T3a/fif/20241210-111304-Epoc X-raw.fif

In [ ]:
import mne

# File paths
T1_file_path = [r'/content/Sumit/T1a/fif/20241210-110330-Epoc X-raw.fif']
T2_file_path = [r'/content/Sumit/T2a/fif/20241210-110820-Epoc X-raw.fif']
T3_file_path = [r'/content/Sumit/T3a/fif/20241210-111304-Epoc X-raw.fif']
T4_file_path = [r'/content/Sumit/T4a/fif/20241210-111818-Epoc X-raw.fif']
T5_file_path = [r'/content/Sumit/T1b/fif/20241210-110551-Epoc X-raw.fif']
T6_file_path = [r'/content/Sumit/T2b/fif/20241210-111041-Epoc X-raw.fif']
T7_file_path = [r'/content/Sumit/T3b/fif/20241210-111524-Epoc X-raw.fif']
T8_file_path = [r'/content/Sumit/T4b/fif/20241210-112128-Epoc X-raw.fif']
# Loop through each file path set
for file_path in T1_file_path:
    try:
        if file_path.endswith('.fif'):
            raw_data = mne.io.read_raw_fif(file_path, preload=True)
            print(f"Loaded {file_path}")
            print(raw_data.info)
        else:
            print(f"Skipping unsupported file type: {file_path}")
    except FileNotFoundError:
        print(f"File not found: {file_path}")
    except Exception as e:
        print(f"An error occurred while loading {file_path}: {e}")

for file_path in T2_file_path:
    try:
        if file_path.endswith('.fif'):
            raw_data = mne.io.read_raw_fif(file_path, preload=True)
            print(f"Loaded {file_path}")
            print(raw_data.info)
        else:
            print(f"Skipping unsupported file type: {file_path}")
    except FileNotFoundError:
        print(f"File not found: {file_path}")
    except Exception as e:
        print(f"An error occurred while loading {file_path}: {e}")

for file_path in T3_file_path:
    try:
        if file_path.endswith('.fif'):
            raw_data = mne.io.read_raw_fif(file_path, preload=True)
            print(f"Loaded {file_path}")
            print(raw_data.info)
        else:
            print(f"Skipping unsupported file type: {file_path}")
    except FileNotFoundError:
        print(f"File not found: {file_path}")
    except Exception as e:
        print(f"An error occurred while loading {file_path}: {e}")

for file_path in T4_file_path:
    try:
        if file_path.endswith('.fif'):
            raw_data = mne.io.read_raw_fif(file_path, preload=True)
            print(f"Loaded {file_path}")
            print(raw_data.info)
        else:
            print(f"Skipping unsupported file type: {file_path}")
    except FileNotFoundError:
        print(f"File not found: {file_path}")
    except Exception as e:
        print(f"An error occurred while loading {file_path}: {e}")

for file_path in T5_file_path:
    try:
        if file_path.endswith('.fif'):
            raw_data = mne.io.read_raw_fif(file_path, preload=True)
            print(f"Loaded {file_path}")
            print(raw_data.info)
        else:
            print(f"Skipping unsupported file type: {file_path}")
    except FileNotFoundError:
        print(f"File not found: {file_path}")
    except Exception as e:
        print(f"An error occurred while loading {file_path}: {e}")

for file_path in T6_file_path:
    try:
        if file_path.endswith('.fif'):
            raw_data = mne.io.read_raw_fif(file_path, preload=True)
            print(f"Loaded {file_path}")
            print(raw_data.info)
        else:
            print(f"Skipping unsupported file type: {file_path}")
    except FileNotFoundError:
        print(f"File not found: {file_path}")
    except Exception as e:
        print(f"An error occurred while loading {file_path}: {e}")

for file_path in T7_file_path:
    try:
        if file_path.endswith('.fif'):
            raw_data = mne.io.read_raw_fif(file_path, preload=True)
            print(f"Loaded {file_path}")
            print(raw_data.info)
        else:
            print(f"Skipping unsupported file type: {file_path}")
    except FileNotFoundError:
        print(f"File not found: {file_path}")
    except Exception as e:
        print(f"An error occurred while loading {file_path}: {e}")

for file_path in T8_file_path:
    try:
        if file_path.endswith('.fif'):
            raw_data = mne.io.read_raw_fif(file_path, preload=True)
            print(f"Loaded {file_path}")
            print(raw_data.info)
        else:
            print(f"Skipping unsupported file type: {file_path}")
    except FileNotFoundError:
        print(f"File not found: {file_path}")
    except Exception as e:
        print(f"An error occurred while loading {file_path}: {e}")


Opening raw data file /content/Sumit/T1a/fif/20241210-110330-Epoc X-raw.fif...
Isotrak not found
    Range : 0 ... 15100 =      0.000 ...   117.969 secs
Ready.
Reading 0 ... 15100  =      0.000 ...   117.969 secs...
Loaded /content/Sumit/T1a/fif/20241210-110330-Epoc X-raw.fif
<Info | 9 non-empty values
 bads: []
 ch_names: TRIGGER, AF3, F7, F3, FC5, T7, P7, O1, O2, P8, T8, FC6, F4, F8, AF4
 chs: 1 Stimulus, 14 EEG
 custom_ref_applied: False
 file_id: 4 items (dict)
 highpass: 0.0 Hz
 lowpass: 64.0 Hz
 meas_date: unspecified
 meas_id: 4 items (dict)
 nchan: 15
 projs: []
 sfreq: 128.0 Hz
>
Opening raw data file /content/Sumit/T2a/fif/20241210-110820-Epoc X-raw.fif...
Isotrak not found
    Range : 0 ... 15197 =      0.000 ...   118.727 secs
Ready.
Reading 0 ... 15197  =      0.000 ...   118.727 secs...
Loaded /content/Sumit/T2a/fif/20241210-110820-Epoc X-raw.fif
<Info | 9 non-empty values
 bads: []
 ch_names: TRIGGER, AF3, F7, F3, FC5, T7, P7, O1, O2, P8, T8, FC6, F4, F8, AF4
 chs: 1 Sti

In [ ]:
import mne

def read_data(file_path):
    ch_names = ['AF3', 'F7', 'F3', 'FC5', 'T7', 'P7', 'O1', 'O2', 'P8', 'T8', 'FC6', 'F4', 'F8', 'AF4']
    # ch_names = [ 'F7', 'F3', 'FC5', 'T7', 'P7', 'O1', 'O2']
    data = mne.io.read_raw_fif(file_path, preload=True)
    data.pick_channels(ch_names)
    # data.set_eeg_reference()
    # data.filter(l_freq=4, h_freq=25)
    epochs = mne.make_fixed_length_epochs(data, duration=5, overlap=4)
    epochs = epochs.get_data()
    print(epochs)
    return epochs

T1_epochs_array = [read_data(subject) for subject in T1_file_path]
T2_epochs_array = [read_data(subject) for subject in T2_file_path]
T3_epochs_array = [read_data(subject) for subject in T3_file_path]
T4_epochs_array = [read_data(subject) for subject in T4_file_path]
T5_epochs_array = [read_data(subject) for subject in T5_file_path]
T6_epochs_array = [read_data(subject) for subject in T6_file_path]
T7_epochs_array = [read_data(subject) for subject in T7_file_path]
T8_epochs_array = [read_data(subject) for subject in T8_file_path]

Opening raw data file /content/Sumit/T1a/fif/20241210-110330-Epoc X-raw.fif...
Isotrak not found
    Range : 0 ... 15100 =      0.000 ...   117.969 secs
Ready.
Reading 0 ... 15100  =      0.000 ...   117.969 secs...
NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).
Not setting metadata
113 matching events found
No baseline correction applied
0 projection items activated
Using data from preloaded Raw for 113 events and 640 original time points ...
0 bad epochs dropped
[[[0.00431308 0.00431397 0.00431436 ... 0.00431449 0.00431218 0.00431154]
  [0.00425385 0.00424756 0.00425013 ... 0.00426487 0.00426128 0.00425654]
  [0.00424    0.00423821 0.00424141 ... 0.00424333 0.00424282 0.00424487]
  ...
  [0.00409449 0.00408949 0.00408885 ... 0.00410013 0.00409782 0.00409397]
  [0.0043259  0.00432385 0.00432526 ... 0.00432987 0.00432923 0.00432423]
  [0.00431256 0.00430833 0.00430808 ... 0.004315   0.00431333 0.00431526]]

 [[0.00431256 0.00431154 0.00431179 ... 0.0043

In [ ]:
print("data files: ",len(T1_epochs_array))
print("epochs: ",len(T1_epochs_array[0]))
print("Channels: ",len(T1_epochs_array[0][0]))
print("data point in each epoch:",len(T1_epochs_array[0][0][0]))

data files:  1
epochs:  113
Channels:  14
data point in each epoch: 640


In [ ]:
print("support T1",len(T1_epochs_array[0]))
print("support T2",len(T2_epochs_array[0]))
print("support T3",len(T3_epochs_array[0]))
print("support T4",len(T4_epochs_array[0]))
print("support T5",len(T5_epochs_array[0]))
print("support T6",len(T6_epochs_array[0]))
print("support T7",len(T7_epochs_array[0]))
print("support T8",len(T8_epochs_array[0]))

support T1 113
support T2 114
support T3 115
support T4 117
support T5 116
support T6 116
support T7 121
support T8 120


In [ ]:
T1_epochs_labels=[len(i)*[0] for i in T1_epochs_array]
T2_epochs_labels=[len(i)*[1] for i in T2_epochs_array]
T3_epochs_labels=[len(i)*[2] for i in T3_epochs_array]
T4_epochs_labels=[len(i)*[3] for i in T4_epochs_array]
T5_epochs_labels=[len(i)*[4] for i in T5_epochs_array]
T6_epochs_labels=[len(i)*[5] for i in T6_epochs_array]
T7_epochs_labels=[len(i)*[6] for i in T7_epochs_array]
T8_epochs_labels=[len(i)*[7] for i in T8_epochs_array]

In [ ]:
from re import T
data_list=T1_epochs_array+T2_epochs_array+T3_epochs_array+T4_epochs_array+T5_epochs_array+T6_epochs_array+T7_epochs_array+T8_epochs_array
label_list=T1_epochs_labels+T2_epochs_labels+T3_epochs_labels+T4_epochs_labels+T5_epochs_labels+T6_epochs_labels+T7_epochs_labels+T8_epochs_labels
print(len(data_list),len(data_list[0]),len(data_list[0][0]),len(data_list[0][0][0]),len(label_list[0]))

8 113 14 640 113


In [ ]:
import numpy as np
data_array=np.vstack(data_list)
label_array=np.hstack(label_list)
print(data_array.shape)
data_array=np.moveaxis(data_array,1,2)

print(data_array.shape,label_array.shape)

(932, 14, 640)
(932, 640, 14) (932,)


In [ ]:
len(data_array[0])

640

In [ ]:
X=data_array
y=label_array

In [ ]:
from tensorflow.keras.layers import Conv1D, BatchNormalization, LeakyReLU, MaxPool1D, \
    GlobalAveragePooling1D, Dense, Dropout, AveragePooling1D
from tensorflow.keras.models import Sequential
from tensorflow.keras.backend import clear_session

def cnnmodel():
    clear_session()
    model = Sequential()

    # First Conv Layer
    model.add(Conv1D(filters=8, kernel_size=3, strides=1, input_shape=(640, 14)))
    model.add(BatchNormalization())
    model.add(LeakyReLU())
    model.add(MaxPool1D(pool_size=2, strides=2))

    # Second Conv Layer
    model.add(Conv1D(filters=8, kernel_size=3, strides=1))
    model.add(BatchNormalization())  # Added BatchNormalization to maintain consistency
    model.add(LeakyReLU())
    model.add(MaxPool1D(pool_size=2, strides=2))
    model.add(Dropout(0.3))

    # Third Conv Layer
    model.add(Conv1D(filters=8, kernel_size=3, strides=1))
    model.add(BatchNormalization())  # Added BatchNormalization
    model.add(LeakyReLU())
    model.add(AveragePooling1D(pool_size=2, strides=2))
    model.add(Dropout(0.3))

    # Fourth Conv Layer
    model.add(Conv1D(filters=8, kernel_size=3, strides=1))
    model.add(BatchNormalization())  # Added BatchNormalization
    model.add(LeakyReLU())
    model.add(AveragePooling1D(pool_size=2, strides=2))

    # Fifth Conv Layer
    model.add(Conv1D(filters=8, kernel_size=3, strides=1))
    model.add(BatchNormalization())  # Added BatchNormalization
    model.add(LeakyReLU())

    # Global Average Pooling and Final Dense Layer for 4 Classes
    model.add(GlobalAveragePooling1D())
    model.add(Dense(8, activation='softmax'))  # Changed to 5 output classes

    # Compile the model for multi-class classification
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

    return model

model = cnnmodel()
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 638, 8)            344       
                                                                 
 batch_normalization (Batch  (None, 638, 8)            32        
 Normalization)                                                  
                                                                 
 leaky_re_lu (LeakyReLU)     (None, 638, 8)            0         
                                                                 
 max_pooling1d (MaxPooling1  (None, 319, 8)            0         
 D)                                                              
                                                                 
 conv1d_1 (Conv1D)           (None, 317, 8)            200       
                                                                 
 batch_normalization_1 (Bat  (None, 317, 8)            3

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np


model = cnnmodel()
accuracy = []

train_features, test_features, train_labels, test_labels = train_test_split(
    data_array, label_array, test_size=0.4, random_state=4
)
train_features, val_features, train_labels, val_labels = train_test_split(
    train_features, train_labels, test_size=0.4, random_state=4
)
# Check the shapes of training features and labels
print("Shape of train_features:", train_features.shape)
print("Shape of train_labels:", train_labels.shape)

# Similarly, check validation and test shapes if needed
print("Shape of val_features:", val_features.shape)
print("Shape of val_labels:", val_labels.shape)
print("Shape of test_features:", test_features.shape)
print("Shape of test_labels:", test_labels.shape)

scaler = StandardScaler()
train_features = scaler.fit_transform(train_features.reshape(-1, train_features.shape[-1])).reshape(train_features.shape)
val_features = scaler.transform(val_features.reshape(-1, val_features.shape[-1])).reshape(val_features.shape)
test_features = scaler.transform(test_features.reshape(-1, test_features.shape[-1])).reshape(test_features.shape)
# Check the shapes of training features and labels
print("Shape of train_features:", train_features.shape)
print("Shape of train_labels:", train_labels.shape)

# Similarly, check validation and test shapes if needed
print("Shape of val_features:", val_features.shape)
print("Shape of val_labels:", val_labels.shape)
print("Shape of test_features:", test_features.shape)
print("Shape of test_labels:", test_labels.shape)



Shape of train_features: (335, 640, 14)
Shape of train_labels: (335,)
Shape of val_features: (224, 640, 14)
Shape of val_labels: (224,)
Shape of test_features: (373, 640, 14)
Shape of test_labels: (373,)
Shape of train_features: (335, 640, 14)
Shape of train_labels: (335,)
Shape of val_features: (224, 640, 14)
Shape of val_labels: (224,)
Shape of test_features: (373, 640, 14)
Shape of test_labels: (373,)


In [ ]:

history = model.fit(train_features, train_labels, epochs=150, batch_size=128, validation_data=(val_features, val_labels))

val_accuracy = model.evaluate(val_features, val_labels)[1]
test_accuracy = model.evaluate(test_features, test_labels)[1]

print("Validation Accuracy:", val_accuracy)
print("Test Accuracy:", test_accuracy)

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import MultiHeadAttention, LayerNormalization, Dropout, Layer
from tensorflow.keras.layers import Dense, Input, GlobalAveragePooling1D, Embedding
from tensorflow.keras.models import Model, Sequential
import numpy as np

class TransformerBlock(Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, rate=0.1):
        super(TransformerBlock, self).__init__()
        self.att = MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim)
        self.ffn = Sequential(
            [Dense(ff_dim, activation="relu"),
             Dense(embed_dim)]
        )
        self.layernorm1 = LayerNormalization(epsilon=1e-6)
        self.layernorm2 = LayerNormalization(epsilon=1e-6)
        self.dropout1 = Dropout(rate)
        self.dropout2 = Dropout(rate)

    def call(self, inputs, training):
        attn_output = self.att(inputs, inputs)
        attn_output = self.dropout1(attn_output, training=training)
        out1 = self.layernorm1(inputs + attn_output)
        ffn_output = self.ffn(out1)
        ffn_output = self.dropout2(ffn_output, training=training)
        return self.layernorm2(out1 + ffn_output)
class TokenAndPositionEmbedding(Layer):
    def __init__(self, maxlen, embed_dim):
        super(TokenAndPositionEmbedding, self).__init__()
        self.pos_emb = Embedding(input_dim=maxlen, output_dim=embed_dim)

    def call(self, x):
        positions = tf.range(start=0, limit=tf.shape(x)[1], delta=1)
        positions = self.pos_emb(positions)
        return x + positions


In [ ]:
# Example EEG dataset
# X_train, X_val: EEG signals as 3D arrays (samples, time, features)
# y_train, y_val: Labels as 1D arrays
# This assumes EEG data has already been preprocessed.
maxlen = 640   # Number of time steps
num_features = 14  # Number of EEG channels or features
num_classes = 8   # Number of classification categories

embed_dim = 32  # Embedding size for each feature
num_heads = 7  # Number of attention heads
ff_dim = 64     # Hidden layer size in feed-forward network

# Input layer
inputs = Input(shape=(maxlen, num_features))

# Positional embedding
positional_encoding = TokenAndPositionEmbedding(maxlen, embed_dim)
x = Dense(embed_dim)(inputs)
x = positional_encoding(x)

# Transformer block
transformer_block = TransformerBlock(embed_dim, num_heads, ff_dim)
x = transformer_block(x)

# Pooling and output
x = GlobalAveragePooling1D()(x)
x = Dropout(0.1)(x)
x = Dense(64, activation="relu")(x)
x = Dropout(0.1)(x)
outputs = Dense(num_classes, activation="softmax")(x)

# Model definition
model = Model(inputs=inputs, outputs=outputs)
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

history = model.fit(train_features, train_labels,
                    batch_size=32,
                    epochs=15,
                    validation_data=(val_features, val_labels))

results = model.evaluate(val_features, val_labels, verbose=2)
for name, value in zip(model.metrics_names, results):
    print(f"{name}: {value:.3f}")


Epoch 1/15
11/11 [==============================] - 112s 10s/step - loss: 1.7652 - accuracy: 0.3731 - val_loss: 1.3075 - val_accuracy: 0.5982
Epoch 2/15
11/11 [==============================] - 110s 10s/step - loss: 1.3127 - accuracy: 0.5254 - val_loss: 1.0440 - val_accuracy: 0.6384
Epoch 3/15
11/11 [==============================] - 109s 10s/step - loss: 1.0493 - accuracy: 0.6836 - val_loss: 0.8409 - val_accuracy: 0.8661
Epoch 4/15
11/11 [==============================] - 109s 10s/step - loss: 0.8739 - accuracy: 0.7403 - val_loss: 0.6970 - val_accuracy: 0.8929
Epoch 5/15
11/11 [==============================] - 109s 10s/step - loss: 0.6999 - accuracy: 0.8239 - val_loss: 0.5904 - val_accuracy: 0.8929
Epoch 6/15
11/11 [==============================] - 109s 10s/step - loss: 0.5814 - accuracy: 0.8299 - val_loss: 0.5034 - val_accuracy: 0.8705
Epoch 7/15
11/11 [==============================] - 109s 10s/step - loss: 0.5197 - accuracy: 0.8478 - val_loss: 0.4340 - val_accuracy: 0.9018
Epoch 

In [ ]:
# Evaluate the model on test data
test_results = model.evaluate(test_features, test_labels, verbose=2)

# Print test results
for name, value in zip(model.metrics_names, test_results):
    print(f"{name}: {value:.3f}")


12/12 - 45s - loss: 0.0948 - accuracy: 0.9946 - 45s/epoch - 4s/step
loss: 0.095
accuracy: 0.995


In [2]:
import tensorflow as tf
from tensorflow.keras.layers import MultiHeadAttention, LayerNormalization, Dropout, Layer
from tensorflow.keras.layers import Dense, Input, GlobalAveragePooling1D, Embedding
from tensorflow.keras.models import Model, Sequential
import numpy as np

class TransformerBlock(Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, rate=0.1):
        super(TransformerBlock, self).__init__()
        self.att = MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim)
        self.ffn = Sequential(
            [Dense(ff_dim, activation="relu"),
             Dense(embed_dim)]
        )
        self.layernorm1 = LayerNormalization(epsilon=1e-6)
        self.layernorm2 = LayerNormalization(epsilon=1e-6)
        self.dropout1 = Dropout(rate)
        self.dropout2 = Dropout(rate)

    def call(self, inputs, training):
        attn_output = self.att(inputs, inputs)
        attn_output = self.dropout1(attn_output, training=training)
        out1 = self.layernorm1(inputs + attn_output)
        ffn_output = self.ffn(out1)
        ffn_output = self.dropout2(ffn_output, training=training)
        return self.layernorm2(out1 + ffn_output)
class TokenAndPositionEmbedding(Layer):
    def __init__(self, maxlen, embed_dim):
        super(TokenAndPositionEmbedding, self).__init__()
        self.pos_emb = Embedding(input_dim=maxlen, output_dim=embed_dim)

    def call(self, x):
        positions = tf.range(start=0, limit=tf.shape(x)[1], delta=1)
        positions = self.pos_emb(positions)
        return x + positions

maxlen = 640   # Number of time steps
num_features = 14  # Number of EEG channels or features
num_classes = 8   # Number of classification categories

embed_dim = 32  # Embedding size for each feature
num_heads = 7  # Number of attention heads
ff_dim = 64     # Hidden layer size in feed-forward network

# Input layer
inputs = Input(shape=(maxlen, num_features))

# Positional embedding
positional_encoding = TokenAndPositionEmbedding(maxlen, embed_dim)
x = Dense(embed_dim)(inputs)
x = positional_encoding(x)

# Transformer block
transformer_block = TransformerBlock(embed_dim, num_heads, ff_dim)
x = transformer_block(x)

# Pooling and output
x = GlobalAveragePooling1D()(x)
x = Dropout(0.1)(x)
x = Dense(64, activation="relu")(x)
x = Dropout(0.1)(x)
outputs = Dense(num_classes, activation="softmax")(x)

# Model definition
model = Model(inputs=inputs, outputs=outputs)


In [3]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 640, 14)]         0         
                                                                 
 dense (Dense)               (None, 640, 32)           480       
                                                                 
 token_and_position_embeddi  (None, 640, 32)           20480     
 ng (TokenAndPositionEmbedd                                      
 ing)                                                            
                                                                 
 transformer_block (Transfo  (None, 640, 32)           33696     
 rmerBlock)                                                      
                                                                 
 global_average_pooling1d (  (None, 32)                0         
 GlobalAveragePooling1D)                                     